// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _3oChallengeDataAccess;

namespace _3oChallengeApp.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20190228100540_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("_3oChallengeDataAccess.ChallengeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Title");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<int?>("UserModelId");

                    b.Property<DateTimeOffset>("ValidFrom");

                    b.Property<DateTimeOffset>("ValidTill");

                    b.Property<string>("WinnerCondition");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.ChallengeUserModel", b =>
                {
                    b.Property<int>("ChallengeId");

                    b.Property<int>("UserId");

                    b.HasKey("ChallengeId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChallengeUserModel");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.InputChallengeAnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int?>("InputChallengeModelId");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("InputChallengeModelId");

                    b.HasIndex("UserId");

                    b.ToTable("InputChallengeAnswers");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.InputChallengeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChallengeId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("InputChallenges");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Photo");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.VoteChallengeAnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.Property<string>("Value");

                    b.Property<int?>("VoteChallengeItemModelId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteChallengeItemModelId");

                    b.ToTable("VoteChallengeAnswers");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.VoteChallengeItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.Property<string>("Value");

                    b.Property<int?>("VoteChallengeModelId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteChallengeModelId");

                    b.ToTable("VoteChallengeItems");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.VoteChallengeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChallengeId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("VoteChallenges");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.ChallengeModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.UserModel")
                        .WithMany("Challenges")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.ChallengeUserModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.ChallengeModel", "Challenge")
                        .WithMany("ChallengeUsers")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_3oChallengeDataAccess.UserModel", "User")
                        .WithMany("ChallengeUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_3oChallengeDataAccess.InputChallengeAnswerModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.InputChallengeModel")
                        .WithMany("Answers")
                        .HasForeignKey("InputChallengeModelId");

                    b.HasOne("_3oChallengeDataAccess.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.InputChallengeModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.ChallengeModel", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.VoteChallengeAnswerModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("_3oChallengeDataAccess.VoteChallengeItemModel")
                        .WithMany("Answers")
                        .HasForeignKey("VoteChallengeItemModelId");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.VoteChallengeItemModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("_3oChallengeDataAccess.VoteChallengeModel")
                        .WithMany("Items")
                        .HasForeignKey("VoteChallengeModelId");
                });

            modelBuilder.Entity("_3oChallengeDataAccess.VoteChallengeModel", b =>
                {
                    b.HasOne("_3oChallengeDataAccess.ChallengeModel", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId");
                });
#pragma warning restore 612, 618
        }
    }
}
